const ERROR_CODE = {
  NO_ERROR: 0,

  // Generic 1~99
  SERVER_TIMEOUT: 1,
  DATABASE_ERROR: 2,

  // Authentication error 100~199
  AUTH_USERNAME_NOT_EXISTED: 100,
  AUTH_WRONG_PASSWORD: 101,
  AUTH_WEAK_PASSWORD: 102,
  AUTH_LOGIN_FAILED_MULTIPLE_TIMES: 103,
  AUTH_ACCOUNT_EXISTED: 104,

  // Authentication error 200~299
  FORM_INVALID_FIELDS: 200,
  FORM_EXISTED: 201,
};

module.export = ERROR_CODE;
